/**
 * Healthline Application Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HealthlineApplicationGateway) {
      root.HealthlineApplicationGateway = {};
    }
    root.HealthlineApplicationGateway.LandingResponse = factory(root.HealthlineApplicationGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LandingResponse model module.
   * @module model/LandingResponse
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>LandingResponse</code>.
   * @alias module:model/LandingResponse
   * @class
   * @param data {Object} 
   */
  var exports = function(data) {
    var _this = this;

    _this['data'] = data;
  };

  /**
   * Constructs a <code>LandingResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LandingResponse} obj Optional instance to populate.
   * @return {module:model/LandingResponse} The populated <code>LandingResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Object} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


