/**
 * Healthline Application Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HealthlineApplicationGateway) {
      root.HealthlineApplicationGateway = {};
    }
    root.HealthlineApplicationGateway.SuggestResponseSuggestions = factory(root.HealthlineApplicationGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SuggestResponseSuggestions model module.
   * @module model/SuggestResponseSuggestions
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>SuggestResponseSuggestions</code>.
   * @alias module:model/SuggestResponseSuggestions
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SuggestResponseSuggestions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SuggestResponseSuggestions} obj Optional instance to populate.
   * @return {module:model/SuggestResponseSuggestions} The populated <code>SuggestResponseSuggestions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cfn')) {
        obj['cfn'] = ApiClient.convertToType(data['cfn'], 'String');
      }
      if (data.hasOwnProperty('imuid')) {
        obj['imuid'] = ApiClient.convertToType(data['imuid'], 'String');
      }
      if (data.hasOwnProperty('rank')) {
        obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} cfn
   */
  exports.prototype['cfn'] = undefined;
  /**
   * @member {String} imuid
   */
  exports.prototype['imuid'] = undefined;
  /**
   * @member {Number} rank
   */
  exports.prototype['rank'] = undefined;



  return exports;
}));


